baseURL = "/"
enableEmoji = true
googleAnalytics = ""
languageCode = "en-us"
rssLimit = 10
theme = ["alpha-church"]
themesDir = "./themes"
title = "Skill Center - Springfield Ohio"

[[menu.main]]
name = "Leaders"
parent = "About"
url = "/leaders"
weight = 2
[[menu.main]]
name = "Blog"
parent = "Resources"
url = "/posts"
weight = 2
[[menu.main]]
name = "Events"
parent = "Resources"
url = "/events"
weight = 1
[[menu.main]]
name = "About Us"
parent = "About"
url = "/about"
weight = 1
[[menu.main]]
name = "Resources"
url = "#"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[params]
customCSS = ["example.css"]
instant_page = true
subtitle = "Serving the community by offering instruction in wood working, graphic arts, and crafts"
title = "Skill Center - Springfield Ohio"
[params.contact]
confirm_page = "/contact_thanks"
service = "netlify"
[params.footer]
copyright = ["skill-center.org"]
[params.landing.CTA]
heading = "Get in touch!"
message = "We'd love to hear from you."
[params.landing.banner]
image = "img/banner.jpg"
[[params.landing.banner.button]]
text = "Get in touch"
url = "#call-to-action"
[[params.landing.banner.button]]
text = "Find out more"
type = "special"
url = "#feature-icons"

[params.landing.feature_icons]
enable = true
[[params.landing.feature_icons.tile]]
accent = "1"
icon = "fa-tools"
icon_pack = "fas"
text = "Retired woodshop teacher available for classes"
title = "Woodshop"
[[params.landing.feature_icons.tile]]
accent = "2"
icon = "fa-tshirt"
icon_pack = "fas"
text = "Come learn T-Shirt printing"
title = "T-Shirt Printing"
[[params.landing.feature_icons.tile]]
accent = "5"
icon = "fa-firstdraft"
icon_pack = "fab"
text = "Come create and have fun"
title = "Crafts"
[[params.landing.feature_icons.tile]]
accent = "3"
icon = "fa-scroll"
icon_pack = "fas"
text = "Coming Soon"
title = "Litho Printing"

[params.landing.feature_images]
enable = true
[[params.landing.feature_images.tile]]
button_text = "Learn more"
image = "img/img_6477.jpg"
title = "Available Projects"
url = "/woodshop-101"
[[params.landing.feature_images.tile]]
button_text = "Learn more"
image = "img/freely-26905.jpg"
text = "Sign up for a class!"
title = "Crafts"
url = "/crafts"

[params.landing.services]
text = "Visit our skill center"
title = "Come take a class"
[[params.links]]
icon = "fa-twitter"
icon_pack = "fab"
link = "//twitter.com/"
service = "Twitter"
[[params.links]]
icon = "fa-facebook"
icon_pack = "fab"
link = "//facebook.com/"
service = "Facebook"
[[params.links]]
icon = "fa-rss"
icon_pack = "fas"
link = "/index.xml"
service = "Full RSS Feed"

[taxonomies]
tag = "tags"
