baseURL = "/"
enableEmoji = true
googleAnalytics = ""
languageCode = "en-us"
rssLimit = 5
theme = ["alpha-church"]
themesDir = "./themes"
title = "Skill Center"
[[menu.main]]
name = "Leaders"
parent = "About"
url = "/leaders"
weight = 2
[[menu.main]]
name = "Blog"
parent = "Resources"
url = "/posts"
weight = 2
[[menu.main]]
name = "Sermons"
parent = "Resources"
url = "/sermons"
weight = 1
[[menu.main]]
name = "About Us"
parent = "About"
url = "/about"
weight = 1
[[menu.main]]
name = "Resources"
url = "#"
weight = 3
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
bible_popups = true
customCSS = ["example.css"]
instant_page = true
subtitle = "Need - add sentence describing business"
title = "Skill Center"
[params.contact]
confirm_page = "/contact_thanks"
service = "netlify"
[params.footer]
copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)", "Design: [HTML5 UP](//html5up.net/alpha)", "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"]
[params.landing.CTA]
heading = "Get in touch!"
message = "We'd love to hear from you."
[params.landing.banner]
image = "img/banner.jpg"
[[params.landing.banner.button]]
text = "Get in touch"
url = "#call-to-action"
[[params.landing.banner.button]]
text = "Find out more"
type = "special"
url = "#feature-icons"
[params.landing.feature_icons]
enable = true
[[params.landing.feature_icons.tile]]
accent = "1"
icon = "fa-hands-helping"
icon_pack = "fas"
text = "Growing people who serve our community."
title = "Serve"
[[params.landing.feature_icons.tile]]
accent = "2"
icon = "fa-church"
icon_pack = "fas"
text = "Meeting together to hear."
title = "Meet"
[[params.landing.feature_icons.tile]]
accent = "5"
icon = "fa-comments"
icon_pack = "fas"
text = "Speaking encouragement to one-another."
title = "Speak"
[[params.landing.feature_icons.tile]]
accent = "3"
icon = "fa-heartbeat"
icon_pack = "fas"
text = "Knowing Love. Being Loved."
title = "Loved"
[params.landing.feature_images]
enable = true
[[params.landing.feature_images.tile]]
button_text = "Learn more"
image = "img/freely-10057.jpg"
text = "A church for the family."
title = "Childrens' Ministry"
url = "/kids"
[[params.landing.feature_images.tile]]
button_text = "Join a group today!"
image = "img/freely-26905.jpg"
text = "Want more during the week?"
title = "Midweek Ministries"
url = "#"
[params.landing.services]
text = "Visit our skill center"
title = "Come take a class"
[params.map]
latitude = "48.8530"
longitude = "2.3498"
zoom = "18"
[params.podcast]
category = "Religion & Spirituality"
copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
email = "test@example.com"
feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"
iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
image = "img/podcast-cover.jpg"
sub_category = "Christianity"
subtitle = ""
summary = "Alpha-Church sermons, talks, messages—podcasted."
title = "Listen to Alpha Church"
[[params.links]]
icon = "fa-twitter"
icon_pack = "fab"
link = "//twitter.com/"
service = "Twitter"
[[params.links]]
icon = "fa-facebook"
icon_pack = "fab"
link = "//facebook.com/"
service = "Facebook"
[[params.links]]
icon = "fa-podcast"
icon_pack = "fas"
link = "/sermons/index.xml"
service = "Podcast"
[[params.links]]
icon = "fa-rss"
icon_pack = "fas"
link = "/index.xml"
service = "Full RSS Feed"
[taxonomies]
preacher = "preachers"
series = "series"
tag = "tags"
